/// Country data with optional predefined cities
class CountryData {
  final String name;
  final List<String>? cities; // null means user can type their own city

  const CountryData(this.name, [this.cities]);
  
  bool get hasPredefinedCities => cities != null && cities!.isNotEmpty;
}

/// All countries in the world - popular ones first, then alphabetical
const List<CountryData> allCountries = [
  // Popular countries with predefined major cities (at the top)
  CountryData('United States', [
    'New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix',
    'Philadelphia', 'San Antonio', 'San Diego', 'Dallas', 'San Jose',
    'Austin', 'Jacksonville', 'San Francisco', 'Miami', 'Seattle',
    'Denver', 'Boston', 'Atlanta', 'Las Vegas', 'Portland'
  ]),
  CountryData('United Kingdom', [
    'London', 'Manchester', 'Birmingham', 'Leeds', 'Glasgow',
    'Liverpool', 'Newcastle', 'Sheffield', 'Bristol', 'Edinburgh',
    'Leicester', 'Brighton', 'Nottingham', 'Cardiff', 'Oxford'
  ]),
  CountryData('Canada', [
    'Toronto', 'Montreal', 'Vancouver', 'Calgary', 'Edmonton',
    'Ottawa', 'Winnipeg', 'Quebec City', 'Hamilton', 'Victoria',
    'Halifax', 'London', 'Kitchener', 'Saskatoon', 'Regina'
  ]),
  CountryData('Australia', [
    'Sydney', 'Melbourne', 'Brisbane', 'Perth', 'Adelaide',
    'Gold Coast', 'Canberra', 'Newcastle', 'Wollongong', 'Hobart',
    'Geelong', 'Townsville', 'Cairns', 'Darwin', 'Toowoomba'
  ]),
  CountryData('Germany', [
    'Berlin', 'Hamburg', 'Munich', 'Cologne', 'Frankfurt',
    'Stuttgart', 'Düsseldorf', 'Dortmund', 'Essen', 'Leipzig',
    'Bremen', 'Dresden', 'Hanover', 'Nuremberg', 'Duisburg'
  ]),
  CountryData('France', [
    'Paris', 'Marseille', 'Lyon', 'Toulouse', 'Nice',
    'Nantes', 'Strasbourg', 'Montpellier', 'Bordeaux', 'Lille',
    'Rennes', 'Reims', 'Le Havre', 'Saint-Étienne', 'Toulon'
  ]),
  CountryData('India', [
    'Mumbai', 'Delhi', 'Bangalore', 'Hyderabad', 'Chennai',
    'Kolkata', 'Pune', 'Ahmedabad', 'Jaipur', 'Surat',
    'Lucknow', 'Kanpur', 'Nagpur', 'Indore', 'Bhopal'
  ]),
  CountryData('Nigeria', [
    'Lagos', 'Kano', 'Ibadan', 'Abuja', 'Port Harcourt',
    'Benin City', 'Kaduna', 'Maiduguri', 'Zaria', 'Aba',
    'Jos', 'Ilorin', 'Oyo', 'Enugu', 'Abeokuta'
  ]),
  CountryData('Brazil', [
    'São Paulo', 'Rio de Janeiro', 'Brasília', 'Salvador', 'Fortaleza',
    'Belo Horizonte', 'Manaus', 'Curitiba', 'Recife', 'Porto Alegre',
  ]),
  CountryData('Mexico', [
    'Mexico City', 'Guadalajara', 'Monterrey', 'Puebla', 'Tijuana',
    'León', 'Juárez', 'Zapopan', 'Mérida', 'Aguascalientes'
  ]),
  CountryData('Philippines', [
    'Manila', 'Quezon City', 'Davao', 'Cebu', 'Makati',
    'Pasig', 'Taguig', 'Parañaque', 'Las Piñas', 'Antipolo'
  ]),
  
  // All other countries alphabetically (users type their own city)
  CountryData('Afghanistan'),
  CountryData('Albania'),
  CountryData('Algeria'),
  CountryData('Andorra'),
  CountryData('Angola'),
  CountryData('Antigua and Barbuda'),
  CountryData('Argentina'),
  CountryData('Armenia'),
  CountryData('Austria'),
  CountryData('Azerbaijan'),
  CountryData('Bahamas'),
  CountryData('Bahrain'),
  CountryData('Bangladesh'),
  CountryData('Barbados'),
  CountryData('Belarus'),
  CountryData('Belgium'),
  CountryData('Belize'),
  CountryData('Benin'),
  CountryData('Bhutan'),
  CountryData('Bolivia'),
  CountryData('Bosnia and Herzegovina'),
  CountryData('Botswana'),
  CountryData('Brunei'),
  CountryData('Bulgaria'),
  CountryData('Burkina Faso'),
  CountryData('Burundi'),
  CountryData('Cambodia'),
  CountryData('Cameroon'),
  CountryData('Cape Verde'),
  CountryData('Central African Republic'),
  CountryData('Chad'),
  CountryData('Chile'),
  CountryData('China'),
  CountryData('Colombia'),
  CountryData('Comoros'),
  CountryData('Congo'),
  CountryData('Costa Rica'),
  CountryData('Croatia'),
  CountryData('Cuba'),
  CountryData('Cyprus'),
  CountryData('Czech Republic'),
  CountryData('Denmark'),
  CountryData('Djibouti'),
  CountryData('Dominica'),
  CountryData('Dominican Republic'),
  CountryData('Ecuador'),
  CountryData('Egypt'),
  CountryData('El Salvador'),
  CountryData('Equatorial Guinea'),
  CountryData('Eritrea'),
  CountryData('Estonia'),
  CountryData('Eswatini'),
  CountryData('Ethiopia'),
  CountryData('Fiji'),
  CountryData('Finland'),
  CountryData('Gabon'),
  CountryData('Gambia'),
  CountryData('Georgia'),
  CountryData('Ghana'),
  CountryData('Greece'),
  CountryData('Grenada'),
  CountryData('Guatemala'),
  CountryData('Guinea'),
  CountryData('Guinea-Bissau'),
  CountryData('Guyana'),
  CountryData('Haiti'),
  CountryData('Honduras'),
  CountryData('Hungary'),
  CountryData('Iceland'),
  CountryData('Indonesia'),
  CountryData('Iran'),
  CountryData('Iraq'),
  CountryData('Ireland'),
  CountryData('Israel'),
  CountryData('Italy'),
  CountryData('Ivory Coast'),
  CountryData('Jamaica'),
  CountryData('Japan'),
  CountryData('Jordan'),
  CountryData('Kazakhstan'),
  CountryData('Kenya'),
  CountryData('Kiribati'),
  CountryData('Kosovo'),
  CountryData('Kuwait'),
  CountryData('Kyrgyzstan'),
  CountryData('Laos'),
  CountryData('Latvia'),
  CountryData('Lebanon'),
  CountryData('Lesotho'),
  CountryData('Liberia'),
  CountryData('Libya'),
  CountryData('Liechtenstein'),
  CountryData('Lithuania'),
  CountryData('Luxembourg'),
  CountryData('Madagascar'),
  CountryData('Malawi'),
  CountryData('Malaysia'),
  CountryData('Maldives'),
  CountryData('Mali'),
  CountryData('Malta'),
  CountryData('Marshall Islands'),
  CountryData('Mauritania'),
  CountryData('Mauritius'),
  CountryData('Micronesia'),
  CountryData('Moldova'),
  CountryData('Monaco'),
  CountryData('Mongolia'),
  CountryData('Montenegro'),
  CountryData('Morocco'),
  CountryData('Mozambique'),
  CountryData('Myanmar'),
  CountryData('Namibia'),
  CountryData('Nauru'),
  CountryData('Nepal'),
  CountryData('Netherlands'),
  CountryData('New Zealand'),
  CountryData('Nicaragua'),
  CountryData('Niger'),
  CountryData('North Korea'),
  CountryData('North Macedonia'),
  CountryData('Norway'),
  CountryData('Oman'),
  CountryData('Pakistan'),
  CountryData('Palau'),
  CountryData('Palestine'),
  CountryData('Panama'),
  CountryData('Papua New Guinea'),
  CountryData('Paraguay'),
  CountryData('Peru'),
  CountryData('Poland'),
  CountryData('Portugal'),
  CountryData('Qatar'),
  CountryData('Romania'),
  CountryData('Russia'),
  CountryData('Rwanda'),
  CountryData('Saint Kitts and Nevis'),
  CountryData('Saint Lucia'),
  CountryData('Saint Vincent and the Grenadines'),
  CountryData('Samoa'),
  CountryData('San Marino'),
  CountryData('Sao Tome and Principe'),
  CountryData('Saudi Arabia'),
  CountryData('Senegal'),
  CountryData('Serbia'),
  CountryData('Seychelles'),
  CountryData('Sierra Leone'),
  CountryData('Singapore'),
  CountryData('Slovakia'),
  CountryData('Slovenia'),
  CountryData('Solomon Islands'),
  CountryData('Somalia'),
  CountryData('South Africa'),
  CountryData('South Korea'),
  CountryData('South Sudan'),
  CountryData('Spain'),
  CountryData('Sri Lanka'),
  CountryData('Sudan'),
  CountryData('Suriname'),
  CountryData('Sweden'),
  CountryData('Switzerland'),
  CountryData('Syria'),
  CountryData('Taiwan'),
  CountryData('Tajikistan'),
  CountryData('Tanzania'),
  CountryData('Thailand'),
  CountryData('Timor-Leste'),
  CountryData('Togo'),
  CountryData('Tonga'),
  CountryData('Trinidad and Tobago'),
  CountryData('Tunisia'),
  CountryData('Turkey'),
  CountryData('Turkmenistan'),
  CountryData('Tuvalu'),
  CountryData('Uganda'),
  CountryData('Ukraine'),
  CountryData('United Arab Emirates'),
  CountryData('Uruguay'),
  CountryData('Uzbekistan'),
  CountryData('Vanuatu'),
  CountryData('Vatican City'),
  CountryData('Venezuela'),
  CountryData('Vietnam'),
  CountryData('Yemen'),
  CountryData('Zambia'),
  CountryData('Zimbabwe'),
];
